// <auto-generated />
using System;
using LMIS.Api.Core.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LMIS.Api.Core.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20231212011802_chengedmodelNaming")]
    partial class chengedmodelNaming
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LMIS.Api.Core.Model.ApplicationUser", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DeletedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Pin")
                        .HasColumnType("integer");

                    b.HasKey("UserId");

                    b.ToTable("ApplicationUsers");
                });

            modelBuilder.Entity("LMIS.Api.Core.Model.BookInventory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BookId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Condition")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DeletedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("BookInventories");
                });

            modelBuilder.Entity("LMIS.Api.Core.Model.CheckoutTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BookId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("BookInventoryId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CheckOutDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsReturned")
                        .HasColumnType("boolean");

                    b.Property<int>("MemberId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BookInventoryId");

                    b.HasIndex("MemberId");

                    b.HasIndex("UserId");

                    b.ToTable("CheckoutTransactions");
                });

            modelBuilder.Entity("LMIS.Api.Core.Model.Genre", b =>
                {
                    b.Property<int>("GenreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("GenreId"));

                    b.Property<DateTime>("DeletedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("MaximumBooksAllowed")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("userId")
                        .HasColumnType("integer");

                    b.HasKey("GenreId");

                    b.HasIndex("userId");

                    b.ToTable("Genres");
                });

            modelBuilder.Entity("LMIS.Api.Core.Model.Member", b =>
                {
                    b.Property<int>("MemberId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MemberId"));

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MemberCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MemberTypeId")
                        .HasColumnType("integer");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("MemberId");

                    b.HasIndex("MemberTypeId")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("Members");
                });

            modelBuilder.Entity("LMIS.Api.Core.Model.MemberType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("MemberTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedOn = new DateTime(2023, 12, 12, 1, 18, 2, 270, DateTimeKind.Utc).AddTicks(3516),
                            IsDeleted = false,
                            Name = "Student"
                        },
                        new
                        {
                            Id = 2,
                            CreatedOn = new DateTime(2023, 12, 12, 1, 18, 2, 270, DateTimeKind.Utc).AddTicks(3519),
                            IsDeleted = false,
                            Name = "Staff"
                        },
                        new
                        {
                            Id = 3,
                            CreatedOn = new DateTime(2023, 12, 12, 1, 18, 2, 270, DateTimeKind.Utc).AddTicks(3520),
                            IsDeleted = false,
                            Name = "Regular Member"
                        },
                        new
                        {
                            Id = 4,
                            CreatedOn = new DateTime(2023, 12, 12, 1, 18, 2, 270, DateTimeKind.Utc).AddTicks(3520),
                            IsDeleted = false,
                            Name = "Premium Member"
                        },
                        new
                        {
                            Id = 5,
                            CreatedOn = new DateTime(2023, 12, 12, 1, 18, 2, 270, DateTimeKind.Utc).AddTicks(3521),
                            IsDeleted = false,
                            Name = "Guest"
                        },
                        new
                        {
                            Id = 6,
                            CreatedOn = new DateTime(2023, 12, 12, 1, 18, 2, 270, DateTimeKind.Utc).AddTicks(3522),
                            IsDeleted = false,
                            Name = "Senior Citezen"
                        },
                        new
                        {
                            Id = 7,
                            CreatedOn = new DateTime(2023, 12, 12, 1, 18, 2, 270, DateTimeKind.Utc).AddTicks(3523),
                            IsDeleted = false,
                            Name = "Corparate Member"
                        });
                });

            modelBuilder.Entity("LMIS.Api.Core.Model.Notification", b =>
                {
                    b.Property<int>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("NotificationId"));

                    b.Property<DateTime>("DeletedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("MemberId")
                        .HasColumnType("integer");

                    b.Property<string>("Messsage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("checkoutTransactionId")
                        .HasColumnType("integer");

                    b.HasKey("NotificationId");

                    b.HasIndex("MemberId");

                    b.HasIndex("UserId");

                    b.HasIndex("checkoutTransactionId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("LMIS.Api.Core.Model.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RoleId"));

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("RoleId");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            IsDeleted = false,
                            RoleName = "Administrator"
                        },
                        new
                        {
                            RoleId = 2,
                            IsDeleted = false,
                            RoleName = "FrontDesk_Officer"
                        },
                        new
                        {
                            RoleId = 3,
                            IsDeleted = false,
                            RoleName = "Management"
                        });
                });

            modelBuilder.Entity("LMIS.Api.Core.Model.UserRole", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("UserRoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserRoleId"));

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("LMIS.Api.Core.Model.CheckoutTransaction", b =>
                {
                    b.HasOne("LMIS.Api.Core.Model.BookInventory", "BookInventory")
                        .WithMany("CheckoutTransactions")
                        .HasForeignKey("BookInventoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LMIS.Api.Core.Model.Member", "Member")
                        .WithMany("CheckoutTransactions")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LMIS.Api.Core.Model.ApplicationUser", "User")
                        .WithMany("CheckoutTransactions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BookInventory");

                    b.Navigation("Member");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LMIS.Api.Core.Model.Genre", b =>
                {
                    b.HasOne("LMIS.Api.Core.Model.ApplicationUser", "user")
                        .WithMany("Genres")
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("user");
                });

            modelBuilder.Entity("LMIS.Api.Core.Model.Member", b =>
                {
                    b.HasOne("LMIS.Api.Core.Model.MemberType", "MemberType")
                        .WithOne()
                        .HasForeignKey("LMIS.Api.Core.Model.Member", "MemberTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LMIS.Api.Core.Model.ApplicationUser", "User")
                        .WithMany("Members")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MemberType");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LMIS.Api.Core.Model.Notification", b =>
                {
                    b.HasOne("LMIS.Api.Core.Model.Member", "Member")
                        .WithMany("Notifications")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LMIS.Api.Core.Model.ApplicationUser", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LMIS.Api.Core.Model.CheckoutTransaction", "CheckoutTransaction")
                        .WithMany()
                        .HasForeignKey("checkoutTransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CheckoutTransaction");

                    b.Navigation("Member");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LMIS.Api.Core.Model.UserRole", b =>
                {
                    b.HasOne("LMIS.Api.Core.Model.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LMIS.Api.Core.Model.ApplicationUser", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LMIS.Api.Core.Model.ApplicationUser", b =>
                {
                    b.Navigation("CheckoutTransactions");

                    b.Navigation("Genres");

                    b.Navigation("Members");

                    b.Navigation("Notifications");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("LMIS.Api.Core.Model.BookInventory", b =>
                {
                    b.Navigation("CheckoutTransactions");
                });

            modelBuilder.Entity("LMIS.Api.Core.Model.Member", b =>
                {
                    b.Navigation("CheckoutTransactions");

                    b.Navigation("Notifications");
                });

            modelBuilder.Entity("LMIS.Api.Core.Model.Role", b =>
                {
                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
